[package]
name = "kiwi-syscall"
version = "0.1.0"
edition = "2024"

[features]
default = ["alloc"]
alloc = ["zerocopy/alloc"]

[dependencies]
zerocopy = { version = "0.8", features = ["derive"] }

[workspace.lints.rust]
undocumented_unsafe_blocks = "warn"
pedantic = "warn"
all = "warn"